export const products = [
  {
    id: 1,
    title: "iPhone 11",
    brand: "Apple",
    image:
      "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1480&q=80",
    price: 60000,
    countInStock: 4,
    rating: 4.3,
    numReviews: 533,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 2,
    title: "iPhone 12",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1612100577176-b976eff1d10c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1390&q=80",
    price: 78000,
    countInStock: 0,
    rating: 4.7,
    numReviews: 1232,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 3,
    title: "GTX 1080Ti",
    brand: "Nvidia",
    image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1470&q=80",
    price: 81000,
    countInStock: 911,
    rating: 4.7,
    numReviews: 3303,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 4,
    title: "Water Cooled PC",
    brand: "NZT",
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80",
    price: 345000,
    countInStock: 911,
    rating: 4.2,
    numReviews: 923,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 5,
    title: "Macbook Pro 16",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1420&q=80",
    price: 290000,
    countInStock: 911,
    rating: 4.6,
    numReviews: 123,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 6,
    title: "Model 3",
    brand: "Tesla",
    image: "https://images.unsplash.com/photo-1561580125-028ee3bd62eb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    price: 7000000,
    countInStock: 911,
    rating: 3.5,
    numReviews: 12,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 7,
    title: "Mustang",
    brand: "Ford",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    price: 9000000,
    countInStock: 911,
    rating: 3.6,
    numReviews: 21,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 8,
    title: "A 7iii",
    brand: "Sony",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=464&q=80",
    price: 150000,
    countInStock: 911,
    rating: 4.6,
    numReviews: 219,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 9,
    title: "Air Pods Pro",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8YWlycG9kcyUyMHByb3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    price: 21000,
    countInStock: 91,
    rating: 3.9,
    numReviews: 33,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 10,
    title: "Air Pods Max",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YWlycG9kcyUyMG1heHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    price: 72000,
    countInStock: 2,
    rating: 3.4,
    numReviews: 3,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 11,
    title: "Boeing 777",
    brand: "Boeing Commercial Airplanes",
    image: "https://images.unsplash.com/photo-1571306603861-20c055ab2e5c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=435&q=80",
    price: 12000000000,
    countInStock: 12,
    rating: 4,
    numReviews: 3,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 12,
    title: "Air Pods",
    brand: "Apple",
    image: "https://images.unsplash.com/photo-1610438235354-a6ae5528385c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YWlycG9kc3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    price: 12000,
    countInStock: 12,
    rating: 4.1,
    numReviews: 622,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
  {
    id: 13,
    title: "Falcon heavy",
    brand: "SpaceX",
    image: "https://images.unsplash.com/photo-1517976487492-5750f3195933?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    price: 420420420,
    countInStock: 12,
    rating: 4.8,
    numReviews: 6969,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae placerat arcu, nec finibus odio. Aenean fermentum sagittis iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
  },
];
